spring:
  application:
    name: erp
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  datasource:
    url: jdbc:postgresql://database-1.cn0u24eg21dc.ap-south-1.rds.amazonaws.com:5432/postgres
    username: VenusAdmin
    password: Venus7#$RR6754
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
    ddl-auto: update
    show-sql: true